KS-3-5 Chess dividing a line
PavelDre/KotlinSprint pull request #15
Opened 2024-02-12 10:51 UTC by PavelDre

нашел я все-таки метод деления строки, опираясь на постоянно имеющиеся разделительные знаки)

2024-02-14 07:43 UTC, ievetrovdev requested changes

2024-02-14 07:43 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson_3_task_5.kt
> +    val whereFromGo = lineStroke.substringBefore("-")
Неплохо, рабочее решение! Но попробуем более оптимальное решение)
Предлагаю применить функцию split(), обрати внимание какие параметры она умеет принимать.

2024-02-15 19:54 UTC, PavelDre commented
Применил функцию split(). Посмотрел что можно работать как с одним, так и с несколькими разделителями. Можно задать определенное количество возвращаемых строк, задав значение limit. Можно игнорировать регистр проверяемой строки с помощью ignorCase = true.
Не смог понять как задавать имя параметрам... вроде бы в интернете  применяют : 
assertThat(info.split(",")).containsExactly("Name", "Year", "Location")
но вообще не понимаю что это. нужно подключить какую то библиотеку? 
может это применяется для массивов, а не для строки? 
Короче сделал вывод через обращение к порядковому номеру элемента в списке. Не знаю на сколько это верное решение.

2024-02-16 13:35 UTC, ievetrovdev requested changes
Как всегда классный ресерч проведен)

По решению немного не нравится повторяющийся код. Не соблюдаем принцип [DRY](https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself). Если изменятся разделители, то придется менять код аш в трех местах.

В связи с этим лучше один раз проинициализировать переменную со списком, а ниже уже доставать из нее по индексам соответствующие значения.

2024-02-16 13:41 UTC, ievetrovdev commented
> Применил функцию split(). Посмотрел что можно работать как с одним, так и с несколькими разделителями. Можно задать определенное количество возвращаемых строк, задав значение limit. Можно игнорировать регистр проверяемой строки с помощью ignorCase = true. Не смог понять как задавать имя параметрам... вроде бы в интернете применяют : assertThat(info.split(",")).containsExactly("Name", "Year", "Location") но вообще не понимаю что это. нужно подключить какую то библиотеку? может это применяется для массивов, а не для строки? Короче сделал вывод через обращение к порядковому номеру элемента в списке. Не знаю на сколько это верное решение.

assertThat это немного вообще в другую сторону. метод используется при написании юнит тестов и является частью библиотеки junit4
https://junit.org/junit4/javadoc/4.13/org/junit/Assert.html

Мы пользуемся сплит и обрати внимание на его сигнатуру. метод имеет ключевое слово varargs - то есть он может принимать произвольное количество параметров. то есть в данном случае разделителей. подробнее тут https://metanit.com/kotlin/tutorial/3.2.php

<img width="969" alt="Снимок экрана 2024-02-16 в 16 40 14" src="https://github.com/PavelDre/KotlinSprint/assets/153023186/a3156c1b-7552-4fb7-9040-ab098aa4e59c">

2024-02-16 17:44 UTC, PavelDre commented
так как по заданию написано что необходимо объявить каждой переменной свое значение я решил что так и необходимо сделать.
исправил код. оставил просто строку, и обращаюсь к ее значениям

2024-02-17 13:18 UTC, ievetrovdev approved these changes

2024-02-17 15:21 UTC, merged