KS-4-3 growing beans
PavelDre/KotlinSprint pull request #18
Opened 2024-02-12 13:24 UTC by PavelDre

Задал благоприятные параметры для выращивания бобов и сравнивал их с вводимыми переменными. 
Трудностей не возникало

2024-02-12 13:25 UTC, PavelDre commented
задал в константы*

2024-02-13 01:26 UTC, ievetrovdev approved these changes

2024-02-13 01:27 UTC, ievetrovdev requested changes

2024-02-13 01:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    val sunnyWeather = true
Лучше использовать более релевантное название. В данном случае для Boolean переменной, которая является своеобразным "флагом" состояния. И для них рекомендуемая конструкция такая: isSunny / isAwningOpen

2024-02-13 01:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +const val SUNNY_WEATHER = true
для булеан констант соответсвенно тоже лучше давать имена с is/has

2024-02-16 14:23 UTC, ievetrovdev approved these changes

2024-02-16 17:01 UTC, merged