KS-4-4 training
PavelDre/KotlinSprint pull request #19
Opened 2024-02-12 13:34 UTC by PavelDre

Думаю что константа INDEX_DAY лишняя... я бы просто оставил в коде "2". Хотя вот сейчас пишу и понимаю, что ей надо было присваивать значение остатка (т.е. 0 или 1) и так же использовать в том логическом выражении.
Просто если подумать как пользователь приложения, я не всегда захочу начать тренировки именно рук и пресса. А значит я могу начать с ног и спины. в этот момент выбора в программе выбирается какая из констант (0 или 1) будет использоваться. Ну а логика работы от этого не поменяется.

2024-02-13 01:30 UTC, ievetrovdev commented
> Думаю что константа INDEX_DAY лишняя... я бы просто оставил в коде "2". Хотя вот сейчас пишу и понимаю, что ей надо было присваивать значение остатка (т.е. 0 или 1) и так же использовать в том логическом выражении. Просто если подумать как пользователь приложения, я не всегда захочу начать тренировки именно рук и пресса. А значит я могу начать с ног и спины. в этот момент выбора в программе выбирается какая из констант (0 или 1) будет использоваться. Ну а логика работы от этого не поменяется.

да лучше ее убрать, сейчас она только усложняет программу. в реальном приложении такая настройка могла бы приходить в параметры функции и в зависимости от нее рассчитывали бы тренировки)

2024-02-13 01:32 UTC, ievetrovdev requested changes

2024-02-13 01:32 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    val indexDay = dayOfTraining % INDEX_DAY == 0
можно удалить `INDEX_DAY`, заменить ее здесь просто двойкой. также давай дадим более логичное название этой переменной, например `isEvenDay`

2024-02-13 01:32 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    val exercisesHands = true
можно не создавать эти переменные, а в выводе просто использовать `isEven / !isEven`

2024-02-15 18:50 UTC, PavelDre commented
Я просто подумал что каждое упражнение должно иметь свое boolean значение. 
Сейчас разгрузил код от лишних переменных.
Отступ по средине так и не смог найти как сделать...( поэтому просто отбил табуляцией

2024-02-16 14:24 UTC, ievetrovdev approved these changes
Отлично! чистая работа в рамках ТЗ

2024-02-16 17:02 UTC, merged