KS-5-1 system anti bot
PavelDre/KotlinSprint pull request #20
Opened 2024-02-12 18:32 UTC by PavelDre

Все понятно

2024-02-13 15:53 UTC, ievetrovdev requested changes

2024-02-13 15:53 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    if (result == RESULT_ANTI_BOT) println("Добро пожаловать!")
Нам необходимо думать об обслуживании и расширяемости кода. Сумма должна считаться автоматически из объявленных заранее переменных.

2024-02-15 19:08 UTC, PavelDre commented
В первом варианте я просто хотел скреативничать, написав вместо 6 букву "б") 
Исправил код для расширяемости

2024-02-16 06:42 UTC, ievetrovdev approved these changes
Креатив приветствуется, но не в ущерб коду и заданию

2024-02-16 17:02 UTC, merged