KS-4-5 ship
PavelDre/KotlinSprint pull request #25
Opened 2024-02-13 06:04 UTC by PavelDre

Здесь вроде тоже трудностей не возникало

2024-02-14 07:55 UTC, ievetrovdev requested changes

2024-02-14 07:55 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val damageShip: Boolean = readln().toBoolean()
по коду все супер, только Boolean переменные принято называть, "отвечая на вопрос“ да/нет. Ну и принято название начинать для них с is, в редких случаях has. Например, `hasDamage`, `isDamaged`. также стоит изменить для переменной погоды и соответствующих констант

2024-02-15 19:00 UTC, PavelDre commented
Исправил наименования переменных и констант с типом boolean

2024-02-16 17:03 UTC, ievetrovdev approved these changes

2024-02-16 17:07 UTC, merged