KS-1-3 Gagarin's flight
PavelDre/KotlinSprint pull request #3
Opened 2024-02-08 14:47 UTC by PavelDre

Время часы 09 и минуты 07 можно задать только типом String. Но вроде бы по заданию нет необходимости выводить именно в таком формате

2024-02-09 16:52 UTC, ievetrov requested changes
Верные рассуждения про строковый тип, предлагаю соблюдать формат из примера. 

Сейчас отклоняю. Чтобы правильно залить изменения, надо:
 - переключиться в Идее на нужную ветку
 - внести изменения и сделать коммит в эту ветку (следить чтобы в стейдж не добавились лишние задачи, которые не относятся к данной задаче)
 - отправить ссылку в бот на этот же пулл реквест к соответствующей задаче

2024-02-09 20:32 UTC, PavelDre commented
Внес изменения в формат вывода в консоль часов и минут вылета. Строковый формат вывода часов и минут прилета добавлять не стал, но в дальнейшем, при решении задач с изменяемым времени считаю что это будет необходимо обязательно.

2024-02-10 06:35 UTC, ievetrovdev approved these changes

2024-02-10 06:35 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +//    println("$hour:$minute")
Верный же вывод, и лучше не оставляй закоментированный код в финальном результате

2024-02-10 06:35 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +    println(hour.toString().padStart(n, '0'))
Интересное решение, но в рамках задания хватило бы и просто строки)

2024-02-10 06:35 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +    var minute: UByte = 7u
Не ошибка, но как правило не используют беззаконные типы данных, только когда это прям нужно. При их использовании возникает больший шанс ошибок, если. туда попадет минусовое значение

2024-02-10 07:13 UTC, merged