KS-1-5 converting seconds to time
PavelDre/KotlinSprint pull request #5
Opened 2024-02-09 21:10 UTC by PavelDre

Для решения этой задачи объявил 2 дополнительные переменные, которые считают часы и минуты. Далее используя функцию (если я ее правильно называю) padStart, которая дает возможность фиксировать количество выводимых символов (в задаче это  переменная n) в toString, и добавляет недостающее количество символов. 
PS узнал что padStart добавляет в начале строки, а padEnd - в конце.

2024-02-09 21:15 UTC, PavelDre commented
Так же хотелось бы добавить, что объявление типа данных Short для секунд здесь получается бесполезным, так как дальнейшие переменные Int, и при их математических действиях, результаты все получаются Int-овыми

2024-02-10 06:40 UTC, ievetrovdev requested changes

2024-02-10 06:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    val minutes = seconds/60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-02-10 06:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    print(hours.toString().padStart(n, '0'))
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение). (может потребовать дополнительного ресерча). Для корректного вывода нуля вначале попробуй посмотреть в сторону String.format().

2024-02-10 16:11 UTC, ievetrovdev approved these changes
Отлично

2024-02-12 09:02 UTC, merged